Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Bed", image_url: "http://www.handfulofsalt.com/wp-content/uploads/2010/04/walnut-white-bed-queen_12.jpg" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Bed", image_url: "http://www.bebitalia.com/App_Uploads/Prodotti/0330/Gallery/big-02-BEB_ITALIA-PAPILIO-02.jpg" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Bed", image_url: "http://server1.oghhk.com/images/i-cdn.apartmenttherapy.com/uimages/la/011508_bo2.jpg" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Bed", image_url: "http://cdn.decorpad.com/photos/2012/02/03/aea0deb6fb23.jpeg" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Bed", image_url: "http://www.conceptfurnishing.co.uk/images/offers/prada-bed.jpg" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Bed", image_url: "http://static.guim.co.uk/sys-images/Guardian/Pix/arts/2005/09/09/eileengrayvandaimagesCnationalmuseumofireAAAAAAAA.jpg" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Bed", image_url: "http://bauhaus-total.com/dbpics/products/1325949090_thHC062_(1).jpg" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Bed", image_url: "http://media.restorationhardware.com/is/image/rhis/cat80018-sp13?wid=696&fmt=jpeg&qlt=90,0&op_sharpen=0&resMode=sharp&op_usm=0.6,1.0,5,0&iccEmbed=1" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Chair", image_url: "http://www.hermanmiller.com/content/dam/hermanmiller/page_assets/products/Eames_Lounge_Chair_and_Ottoman/hero_eames_lounge_2.jpg" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Chair", image_url: "http://www.stylepark.com/db-images/cms/bbitalia/img/l2_p333466_488_336-1.jpg" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Chair", image_url: "http://media.tumblr.com/tumblr_kxcgy3c6ux1qzmzzy.jpg" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Chair", image_url: "http://img.homeportfolio.com/cms/550849/abc-carpet-home-chairs-ottomans-500.jpg" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Chair", image_url: "http://www.housebeautiful.com/cm/housebeautiful/images/JW/07-hbx-target-mid-century-modern-zig-zag-chair-lgn.jpg" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Chair", image_url: "http://static1.bonluxat.com/cmsense/data/uploads/orig/preben-fabricius-and-j%C3%B8rgen-kastholm-fk-armchair_4c33.jpg" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Chair", image_url: "http://p2.la-img.com/176/18655/6311633_1_l.jpg" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Chair", image_url: "http://www.blessthisstuff.com/imagens/stuff/img_copenhagen_chair.jpg" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Sofa", image_url: "http://st.houzz.com/simgs/b7319bd501acfeb6_4-1896/sofas.jpg" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Sofa", image_url: "http://image.architonic.com/img_pfm2-2/200/0248/harry_966_b.jpg" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Sofa", image_url: "http://housetohome.media.ipcdigital.co.uk/96/000014f7b/da69_orh550w550/07-BoConcept.jpg" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Sofa", image_url: "http://img.homeportfolio.com/cms/550945/abc-carpet-home-sofas-500.jpg" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Sofa", image_url: "http://cdn.decoist.com/wp-content/uploads/2011/10/The-Missoni-Home-Round-Tiamat-200-Sofa-1.jpg" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Sofa", image_url: "http://cdn.pursuitist.com/wp-content/uploads/2014/04/Versace_Palazzo_couch.jpg" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Sofa", image_url: "http://www.fallingpixel.com/products/27858/mains/0000-montecarlo6.jpg" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Sofa", image_url: "http://media.restorationhardware.com/is/image/rhis/prod2430257_av1?$l-pd1$" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Table", image_url: "http://www.retrofurnish.us/media/catalog/product/cache/8/image/1200x/5eac9d8dbe0434db616a3875635e2979/e/l/ellipse-table-inspired-by-charles-eames-3.jpg" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Table", image_url: "http://image.architonic.com/img_pro2-1/102/7824/the_table_03_b.jpg" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Table", image_url: "http://cdn.freshome.com/wp-content/uploads/2010/10/coffee-table-bo-concept1.jpg" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Table", image_url: "http://img.homeportfolio.com/cms/550733/abc-carpet-home-dining-tables-500.jpg" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Table", image_url: "http://www.designboom.com/cms/images/andrea01/brizio03.jpg" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Table", image_url: "http://www.wharfside.co.uk/images/uploads/products/prada-flaye-table.jpg" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Table", image_url: "http://hivemodern.com/public_resources/rivoli-eileen-gray-classicon-1.jpg" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Table", image_url: "http://media.restorationhardware.com/is/image/rhis/prod1606015_R12?$l-pd1$" })
