Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Bed" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Bed" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Bed" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Bed" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Bed" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Bed" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Bed" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Bed" })
Product.create({ name: "Cesca", price: "2000", original_price: "7000", furniture_type: "Bed" })
Product.create({ name: "Walmart", price: "6500", original_price: "45000", furniture_type: "Bed" })
Product.create({ name: "Zara", price: "7600", original_price: "8770", furniture_type: "Bed" })
Product.create({ name: "Urban Outfitters", price: "6700", original_price: "22000", furniture_type: "Bed" })
Product.create({ name: "Blu", price: "4500", original_price: "8770", furniture_type: "Bed" })
Product.create({ name: "CB2", price: "1100", original_price: "7000", furniture_type: "Bed" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Desk" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Desk" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Desk" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Desk" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Desk" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Desk" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Desk" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Desk" })
Product.create({ name: "Cesca", price: "2000", original_price: "7000", furniture_type: "Desk" })
Product.create({ name: "Walmart", price: "6500", original_price: "45000", furniture_type: "Desk" })
Product.create({ name: "Zara", price: "7600", original_price: "8770", furniture_type: "Desk" })
Product.create({ name: "Urban Outfitters", price: "6700", original_price: "22000", furniture_type: "Desk" })
Product.create({ name: "Blu", price: "4500", original_price: "8770", furniture_type: "Desk" })
Product.create({ name: "CB2", price: "1100", original_price: "7000", furniture_type: "Desk" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Chair" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Chair" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Chair" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Chair" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Chair" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Chair" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Chair" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Chair" })
Product.create({ name: "Cesca", price: "2000", original_price: "7000", furniture_type: "Chair" })
Product.create({ name: "Walmart", price: "6500", original_price: "45000", furniture_type: "Chair" })
Product.create({ name: "Zara", price: "7600", original_price: "8770", furniture_type: "Chair" })
Product.create({ name: "Urban Outfitters", price: "6700", original_price: "22000", furniture_type: "Chair" })
Product.create({ name: "Blu", price: "4500", original_price: "8770", furniture_type: "Chair" })
Product.create({ name: "CB2", price: "1100", original_price: "7000", furniture_type: "Chair" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Sofa" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Sofa" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Sofa" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Sofa" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Sofa" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Sofa" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Sofa" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Sofa" })
Product.create({ name: "Cesca", price: "2000", original_price: "7000", furniture_type: "Sofa" })
Product.create({ name: "Walmart", price: "6500", original_price: "45000", furniture_type: "Sofa" })
Product.create({ name: "Zara", price: "7600", original_price: "8770", furniture_type: "Sofa" })
Product.create({ name: "Urban Outfitters", price: "6700", original_price: "22000", furniture_type: "Sofa" })
Product.create({ name: "Blu", price: "4500", original_price: "8770", furniture_type: "Sofa" })
Product.create({ name: "CB2", price: "1100", original_price: "7000", furniture_type: "Sofa" })

Product.create({ name: "Eames", price: "7777", original_price: "15000", furniture_type: "Table" })
Product.create({ name: "B&B Italia", price: "5555", original_price: "13000", furniture_type: "Table" })
Product.create({ name: "BoConcept", price: "5000", original_price: "7000", furniture_type: "Table" })
Product.create({ name: "ABC Home", price: "7000", original_price: "22000", furniture_type: "Table" })
Product.create({ name: "Target", price: "6500", original_price: "45000", furniture_type: "Table" })
Product.create({ name: "Prada", price: "5000", original_price: "8770", furniture_type: "Table" })
Product.create({ name: "Eilen Gray", price: "9000", original_price: "22000", furniture_type: "Table" })
Product.create({ name: "Restoration Hardware", price: "4000", original_price: "8770", furniture_type: "Table" })
Product.create({ name: "Cesca", price: "2000", original_price: "7000", furniture_type: "Table" })
Product.create({ name: "Walmart", price: "6500", original_price: "45000", furniture_type: "Table" })
Product.create({ name: "Zara", price: "7600", original_price: "8770", furniture_type: "Table" })
Product.create({ name: "Urban Outfitters", price: "6700", original_price: "22000", furniture_type: "Table" })
Product.create({ name: "Blu", price: "4500", original_price: "8770", furniture_type: "Table" })
Product.create({ name: "CB2", price: "1100", original_price: "7000", furniture_type: "Table" })

